version: "3"

services:
  web:
    build: .
    ports:
      - "8001:8001"
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8001"

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "27017"
    volumes:
      - data:/bitnami/mongodb


volumes:
  data: